### ISSUE TITLE
Shipping address not correct

### ISSUE THREAD

**Issue by tripex** [CoolRunner-dk/woocommerce-coolrunner#1]
When selecting DAO pakkeshop delivery, the delivery address is stil shown as the customers homeaddress instead of the selected pakkeshop.

**Comment by KevinSHansen** [comment]
> When selecting DAO pakkeshop delivery, the delivery address is stil shown as the customers homeaddress instead of the selected pakkeshop.

The "pakkeshop" address should be added in a new table next to those prices. Isnt that the case?

**Comment by KevinSHansen** [comment]
Due to no reply on last answer we see this issue as solved.

Please open a new issue if this isn't solved :)
